# Eigenvalues and Eigenvectors

An eigenvalue problem is a problem of the form 
$$A \vec{x} = \lambda \vec{x},\ \ \ \ \ \ \ \ (1)$$
where $A$ is an $n \times n$ matrix of real or complex values, $\vec{x}$ is a non-zero $n \times 1$ vector and $\lambda$ is a scalar. Both $\vec{x}$ or $\lambda$ may be real or comlex. The values of $\lambda$ for which this equation has a solution are called eigenvalues of the matrix. The vector $\vec{x}$ which correspnds to each eigenvalue is called an eigenvector of the matrix.

Eq. (1) can be rewritten as:
$$(A - \lambda I) \vec{x} = 0,\ \ \ \ \ \ \ \ (2)$$
where $I$ is the identity matrix.

The eigenvalues of the matrix $A$ are the roots of the polynomial
$$p_{A}(\lambda) = det(A - \lambda I),\ \ \ \ \ \ \ \ (3)$$
which is called the *characteristic polynomial* of the matrix.

The eigenvectors corresponding to an eigenvalue $\lambda$ are found by solving the system of linear equations given by Eq. (2).

It is important to note that every vector that satisfies Eq. (1) is an eigenvector of the matrix. That means that there is an infinite number of eigenvectors for a  given matrix.

A nice tutorial on how to calculate eigenvalues and eigenvectors can be found [here](http://www.sosmath.com/matrix/eigen2/eigen2.html).

## Eigenvalues and eigenvectors in Python

In Python we can make use of NumPy's [**linalg.eig(a)**](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.linalg.eig.html) function, which takes as input a square matrix **a** and returns a tuple of arrays **(w, v)**, where **w** are the eigenvalues of the matrix and **v** their corresponding normalized (unit "length") eigenvectors, such that the column ```v[:,i]``` is the eigenvector corresponding to the eigenvalue ```w[i]```.

### Example

Suppose we have the following square matrix:
$$A =
\begin{bmatrix}
1 & -3 & 3 \\
3 & -5 & 3 \\
6 & -6 & 4
\end{bmatrix}$$

In [57]:
from numpy import linalg as LA
import numpy as np

In [58]:
A = np.matrix([[1, -3, 3], [3, -5, 3], [6, -6, 4]])
A

matrix([[ 1, -3,  3],
        [ 3, -5,  3],
        [ 6, -6,  4]])

We calculate the matrix's eigenvalues and eigenvectors. We should, however, be careful, because ```linalg.eig(a)``` is prone to *roundoff errors*, as seen for ```evals = -2```.

In [59]:
evals, evecs = LA.eig(A)
print("Evals:\n", evals)
print()
print("Evecs:\n", evecs)

Evals:
 [ 4. +0.00000000e+00j -2. +1.10465796e-15j -2. -1.10465796e-15j]

Evecs:
 [[-0.40824829+0.j          0.24400118-0.40702229j  0.24400118+0.40702229j]
 [-0.40824829+0.j         -0.41621909-0.40702229j -0.41621909+0.40702229j]
 [-0.81649658+0.j         -0.66022027+0.j         -0.66022027-0.j        ]]


Check that all eigenvectors are normalized.

In [60]:
for i in range(3):
    evsum = 0
    for j in range(3):
        evsum += abs(evecs[j, i])**2
    print("Evec{:d} = {:.5f}".format(i, evsum))

Evec0 = 1.00000
Evec1 = 1.00000
Evec2 = 1.00000


Check that evecs are indeed the eigenvectors of matrix $A$ by utilizing Eq. (1). We also use NumPy's **round()** function to take care of roundoff errors.

In [61]:
np.round(np.dot(A, evecs[:, 2]), 5)

matrix([[-0.48800-0.81404j],
        [ 0.83244-0.81404j],
        [ 1.32044+0.j     ]])

In [62]:
np.round(np.dot(evals[2], evecs[:, 2]), 5)

matrix([[-0.48800-0.81404j],
        [ 0.83244-0.81404j],
        [ 1.32044+0.j     ]])

We can have the matrix, eigenvalues and eigenvectors printed in a prettier form using SymPy's [**Matrix()** and **eigenvects()**](http://docs.sympy.org/latest/tutorial/matrices.html) functions.

In [63]:
import sympy as sp
sp.init_printing(use_unicode=True)

In [64]:
symbA = sp.Matrix(A)
symbA

⎡1  -3  3⎤
⎢        ⎥
⎢3  -5  3⎥
⎢        ⎥
⎣6  -6  4⎦

In [65]:
symbA.eigenvects()

⎡⎛       ⎡⎡1⎤  ⎡-1⎤⎤⎞  ⎛      ⎡⎡1/2⎤⎤⎞⎤
⎢⎜       ⎢⎢ ⎥  ⎢  ⎥⎥⎟  ⎜      ⎢⎢   ⎥⎥⎟⎥
⎢⎜-2, 2, ⎢⎢1⎥, ⎢0 ⎥⎥⎟, ⎜4, 1, ⎢⎢1/2⎥⎥⎟⎥
⎢⎜       ⎢⎢ ⎥  ⎢  ⎥⎥⎟  ⎜      ⎢⎢   ⎥⎥⎟⎥
⎣⎝       ⎣⎣0⎦  ⎣1 ⎦⎦⎠  ⎝      ⎣⎣ 1 ⎦⎦⎠⎦